/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.compensar.redsocial.swing;

/**
 *
 * @author LENOVO
 */
public class InicioSesionScreen extends javax.swing.JFrame {

    /**
     * Creates new form inicioSesion
     */
    public InicioSesionScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Body = new javax.swing.JPanel();
        Section1 = new javax.swing.JLabel();
        Section2 = new javax.swing.JPanel();
        Content = new javax.swing.JPanel();
        Bienvenida = new javax.swing.JLabel();
        BienvenidaSubtittle = new javax.swing.JLabel();
        RegistroPanel = new javax.swing.JPanel();
        RegistroLable = new javax.swing.JLabel();
        RegistrarButton = new javax.swing.JButton();
        EmailLable = new javax.swing.JLabel();
        EmailTextfield = new javax.swing.JTextField();
        ContrasenaLable = new javax.swing.JLabel();
        ContrasenaPasswordField = new javax.swing.JPasswordField();
        IniciarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        Body.setForeground(new java.awt.Color(255, 255, 255));

        Section2.setBackground(new java.awt.Color(255, 255, 255));

        Content.setBackground(new java.awt.Color(255, 255, 255));
        Content.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(216, 215, 215)));

        Bienvenida.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        Bienvenida.setForeground(new java.awt.Color(107, 20, 166));
        Bienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bienvenida.setText("¡Te damos la bienvenida!");

        BienvenidaSubtittle.setBackground(new java.awt.Color(255, 255, 255));
        BienvenidaSubtittle.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        BienvenidaSubtittle.setForeground(new java.awt.Color(115, 115, 115));
        BienvenidaSubtittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BienvenidaSubtittle.setText("Completa los detalles a continuación para empezar.");
        BienvenidaSubtittle.setVerifyInputWhenFocusTarget(false);

        RegistroPanel.setBackground(new java.awt.Color(255, 255, 255));

        RegistroLable.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        RegistroLable.setForeground(new java.awt.Color(115, 115, 115));
        RegistroLable.setText("¿No tienes una cuenta? Registrate");
        RegistroLable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        RegistrarButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        RegistrarButton.setForeground(new java.awt.Color(107, 20, 166));
        RegistrarButton.setText("aquí");
        RegistrarButton.setBorder(null);
        RegistrarButton.setBorderPainted(false);
        RegistrarButton.setContentAreaFilled(false);
        RegistrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegistroPanelLayout = new javax.swing.GroupLayout(RegistroPanel);
        RegistroPanel.setLayout(RegistroPanelLayout);
        RegistroPanelLayout.setHorizontalGroup(
            RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(RegistroLable, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegistrarButton)
                .addGap(35, 35, 35))
        );
        RegistroPanelLayout.setVerticalGroup(
            RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistroLable)
                    .addComponent(RegistrarButton))
                .addGap(0, 0, 0))
        );

        EmailLable.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        EmailLable.setForeground(new java.awt.Color(115, 115, 115));
        EmailLable.setText("Correo electronico");

        EmailTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextfieldActionPerformed(evt);
            }
        });

        ContrasenaLable.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        ContrasenaLable.setForeground(new java.awt.Color(115, 115, 115));
        ContrasenaLable.setText("Contraseña");

        ContrasenaPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrasenaPasswordFieldActionPerformed(evt);
            }
        });

        IniciarButton.setBackground(new java.awt.Color(107, 20, 166));
        IniciarButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        IniciarButton.setForeground(new java.awt.Color(255, 255, 255));
        IniciarButton.setText("Iniciar Sesión");
        IniciarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BienvenidaSubtittle, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
            .addComponent(RegistroPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 325, Short.MAX_VALUE)
            .addGroup(ContentLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ContrasenaLable)
                    .addComponent(EmailLable)
                    .addComponent(EmailTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(ContrasenaPasswordField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(IniciarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Bienvenida)
                .addGap(10, 10, 10)
                .addComponent(BienvenidaSubtittle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegistroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(EmailLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ContrasenaLable)
                .addGap(2, 2, 2)
                .addComponent(ContrasenaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IniciarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout Section2Layout = new javax.swing.GroupLayout(Section2);
        Section2.setLayout(Section2Layout);
        Section2Layout.setHorizontalGroup(
            Section2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Section2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        Section2Layout.setVerticalGroup(
            Section2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Section2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Section1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Section2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Section1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Section2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmailTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextfieldActionPerformed

    private void ContrasenaPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrasenaPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContrasenaPasswordFieldActionPerformed

    private void IniciarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IniciarButtonActionPerformed

    private void RegistrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarButtonActionPerformed
        RegistroScreen registroSn = new RegistroScreen();
        registroSn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegistrarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesionScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenida;
    private javax.swing.JLabel BienvenidaSubtittle;
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Content;
    private javax.swing.JLabel ContrasenaLable;
    private javax.swing.JPasswordField ContrasenaPasswordField;
    private javax.swing.JLabel EmailLable;
    private javax.swing.JTextField EmailTextfield;
    private javax.swing.JButton IniciarButton;
    private javax.swing.JButton RegistrarButton;
    private javax.swing.JLabel RegistroLable;
    private javax.swing.JPanel RegistroPanel;
    private javax.swing.JLabel Section1;
    private javax.swing.JPanel Section2;
    // End of variables declaration//GEN-END:variables
}
